### ISSUE TITLE
Running the server on the remarkable fails

### ISSUE THREAD

**Issue by amlwwalker** [LinusCDE/rmWacomToMouse#1]
Hi,
I've ssh'd into my remarkable tablet, and scp'd the binary across to it, changed the permissions so that its executable, but when I run it I get;

```
remarkable: ~/ ./rmServeWacomInput
-sh: ./rmServeWacomInput: No such file or directory
```

```
remarkable: ~/ ls -l
-rwxrwxrwx    1 root     root          8328 Mar  9 17:09 rmServeWacomInput
```

Any ideas why, this would usually mean its running on a 32bit/64bit incompatible version, but as you made this for the remarkable I don't imagine thats the issue?

Thanks
A

**Comment by amlwwalker** [comment]
Scratch that, something changed and not its working. I *think* it was that the linker is in /opt but that wasn't accessible until after I installed the package manager for remarkable from here https://github.com/Evidlo/remarkable_entware

**Comment by LinusCDE** [comment]
Hi. Sorry but for some reason I didn't receive an E-Mail (or the notofication) on this issue.
I've recently noticed myself that a library from /opt was necessary because I compiled the binary using the gcc from entware.
The latest binary was compiled using the crossplatform-toolchain which created a binary that runs without any mods to the reMarkable.
